### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by sebastien17** [superseva/mutant-year-zero#13]
Hi supernova,

Thank you for your awesome work on MYZ.
Still new to Foundry but I have prepared the french translation.
I am not sure  for all the translations cause I have no access to a french copy of the book but I think it is a good basis to start.

See you
[fr.zip](https://github.com/superseva/mutant-year-zero/files/5932308/fr.zip)

**Comment by superseva** [comment]
Hey, thanks a lot.
I am pushing some small changes tomorrow so I will push French with those.

**Comment by superseva** [comment]
It's implemented
