### ISSUE TITLE
Dice Roll Issue

### ISSUE THREAD

**Issue by Marsi84** [superseva/mutant-year-zero#15]
Superseva, thank you so much for your hard work!
I have a problem with dices.

When rolling special dices, 6 are not recognized as success.
e.g., I roll 2 dices for attribute, 2 for skills and 2 for gears with the command below and want to count successes.

/r 2dbcs6+2dscs6+2dgcs6

however, this would return me the number of dices rolled, not the number of 6 rolled.
Can this be fixed?

(btw I tried on the official Forbidden Lands Game System and it works there)

Thank you!

**Comment by superseva** [comment]
I'll take a look

**Comment by superseva** [comment]
it's fixed

**Comment by Marsi84** [comment]
Thank you!!!
