### ISSUE TITLE
Spanish translation for the skills compendium.

### ISSUE THREAD

**Issue by parvusdomus** [superseva/mutant-year-zero#18]
Hello superseva,

I see the es.json file for the spanish translation is already uploaded but I noticed that all the char sheet is translated but the skills are not altered when using that file. So I had a look and noticed that for them to be translated the skills compendium needed to be translated too so I did and created a translation file for Babele. I can send it to you if you want to include it (and enable babele translations) or I could create my own translation module (for the skill compendium only). Please let me know your thoughts.

Regards
ParvusDomus

**Comment by superseva** [comment]
I think it's best to leave sheet/system independent from any modules (including babel).
There are 3 ways you can translate actual skills.
1.I will soon introduce 'soft' translate of the character sheet skill list.( skill names on the sheet being displayed in the selected language based on the skillKey). (This is will not translate skill items in compendium, it will just display their name in the character sheet).
2. You can duplicate core-skills.db , translate it completely (also populate their description too) and then just paste it over "core-skills.db" that comes with the system. (system handles skills by their "skillKey" parameter so you can easily change names). This will be overridden by the system update so keep a copy at hand. This is how homemade skill compendium is handled anyway. It's the best way to have the compendium in the language you want with the descriptions in the same language too)
3. Do a module or just macro that will change the names of the skills in actors and/or core-skill.db compendium.

**Comment by parvusdomus** [comment]
Hello superseva,
Option 1 sounds great and more than enough for me (I don't need the compendium translated, with the charsheet is more than enough). I understand you are taking the translations from the es.js file, right? If you need anything else or any additional file translated, just let me know I'll be glad to help translating it.
Thanks a lot for your great work, have an amazing day
