### ISSUE TITLE
Skills don't translate in french

### ISSUE THREAD

**Issue by Gyaile** [superseva/mutant-year-zero#23]
Hi,
first time reporting an issue on github, sorry if i do it wrong.
There is some errors in the fr.son files. All the skills begin with MYZ.SKILLS_NameOfSkill instead of MYZ.SKILL_NameOfSkill. Therefore, the attributs are not translated.
I made a file with the errors corrected and some translations updated. Tell me if you want it.
Hope this help.

**Comment by superseva** [comment]
hey Gyaile, thanks for reporting. Sure, send the updated file my way and I will include it with the new update.
If you don't mind you can send it on superseva@gmail.com since github produced some errors with sending json files through the reply.
Thanks
