### ISSUE TITLE
Intimidate skill

### ISSUE THREAD

**Issue by cyberdwarf1664** [superseva/mutant-year-zero#25]
It seems this skill is missing in the compendium

thanks

Edit : My mistake, there are no specialized skills...

**Comment by cyberdwarf1664** [comment]
Hello,
other specialized skills are not integrated.
As soon as all the skills are integrated, if it can help you, I can translate the compendium with Bablele.

**Comment by superseva** [comment]
Oh, the specialization skills are not included in the system free version because they are not used in the character creation. The Skill Pack is only used to prepopulate characters with the list of general skills.

**Comment by superseva** [comment]
I might add them in the 0.8 release since I have the translations included for the official release if the Core Book
