### ISSUE TITLE
Undefined strings after translating Actor types

### ISSUE THREAD

**Issue by Phenomen** [superseva/mutant-year-zero#27]
I translated actor types in the same way I do it for other systems:

```json
  "ACTOR": {
    "TypeAnimal": "Зверь",
    "TypeArk": "Ковчег",
    "TypeHuman": "Человек",
    "TypeMutant": "Мутант",
    "TypeNpc": "NPC",
    "TypeRobot": "Робот"
  }
```

After that all type-specific strings in the character sheet become bugged:

![FoundryVTT_PuJfHE6JH9](https://user-images.githubusercontent.com/138311/118901653-6e20f600-b8d9-11eb-9cc8-6ca54505c195.png)

**Comment by superseva** [comment]
Look at the translation json file
it should be:
ACTOR.TypeAnimal": "Animal", 
"ACTOR.TypeArk": "Ark", 
"ACTOR.TypeHuman": "Human",
"ACTOR.TypeMutant": "Mutant", 
"ACTOR.TypeNpc": "NPC",
"ACTOR.TypeRobot": "Robot"

**Comment by superseva** [comment]
is this 7.9 or 8x Beta ?

**Comment by Phenomen** [comment]
> Look at the translation json file
> it should be:
> ACTOR.TypeAnimal": "Animal",
> "ACTOR.TypeArk": "Ark",
> "ACTOR.TypeHuman": "Human",
> "ACTOR.TypeMutant": "Mutant",
> "ACTOR.TypeNpc": "NPC",
> "ACTOR.TypeRobot": "Robot"

Structured JSON works just as Flat JSON. At least I never issue with any other module or system when using this format.

Foundry 0.8.4. I guess that's why...

**Comment by superseva** [comment]
yeah they should that's why I guessed you are using beta
