### ISSUE TITLE
Missing Item controls

### ISSUE THREAD

**Issue by J0N7E** [superseva/mutant-year-zero#37]
Missing item controls for edit and trash in artifacts.html, gear.html, criticals.html, mutations.html and talents.html.

<img width="291" alt="Skärmbild 2021-07-27 120543" src="https://user-images.githubusercontent.com/17961458/127137001-ec5f3e47-6805-4241-b619-afda178615a5.png">

**Comment by superseva** [comment]
Right click on the item for edit/delete menu should work
