### ISSUE TITLE
Swedish translation not by the book

### ISSUE THREAD

**Issue by JohnBaystream** [superseva/mutant-year-zero#40]
Hi
Not sure if this is the right place to ask this.

Love the work you have put down in this Foundry system. 

I'm from Sweden and play MY0 in swedish. I will definitely try it out when i start using Foundry. 

However when I look at the swedish translation it doesn't exactly follow the swedish wordings in the swedish books. 

You want help changing the few words that are off or should I only change it in my foundry?

Another thing they did in the swedish version concerning the animals is that their skill Sense emotion isnt called Sense Emotion it's called Sniffing. So i cant change that in the translation since there is only one Sense Emotion.

**Comment by superseva** [comment]
Hey John,
thanks for looking into it. The SE translation is provided by the community members. 
If you want you can look at the swedish json located in the lang/se.json.
You can make your copy.edit and I can see to include the changes when I am back from vacation.
I am not swedish speaker so I am not sure if the previous translator maybe took in consideration that some translations are 'to long' ( to many letters so it doesn't fit) but I think the more official the translation is the better.

SE translation is missing these lines  too:
```
"SETTINGS.ApplyPushTraumaN": "Apply Push Trauma",
"SETTINGS.ApplyPushTraumaH": "Whether to apply trauma from banes on pushed rolls.",
"SETTINGS.ApplyPushGearDamageN": "Apply Push Gear Damage",
"SETTINGS.ApplyPushGearDamageH": "Whether to apply gear damage from banes on pushed rolls."
```
so if you can you can send me the translations for those too.

I think sense_emotion is translated as "Sniffa" in the se.json file. The whole system is built based on the english translation, same as  the official module so that is why there is only one skill for that.
 if you have problem making your push release you can just send me edited json on my email
superseva@gmail.com
Tnx again for the help

**Comment by JohnBaystream** [comment]
Hi

I will look into this.

I´ve tried my own changes before i contacted you and i didnt see any problem with the words being to long.

Sense Emotion is called "Genomskåda" for mutants and and humans but "Sniffa" för animals. So i would go with "Genomskåda" if we can't change it so the animals get their own Sense Emotion in english. I'm not that good with my coding skills so i can make that change work. It works fine as long as you accept that the skill get another name for the animals. No problem with push as i can see.

Are "ones" on base dice called banes in mutant? Only seen this with Forbidden lands but i dont use english versions when i play so i might have missed that,.

Wish i could more about coding then i would make game systems for my other favorite games and use the year zero engine for them.

24 augusti 2021 15:42:30 +02:00, skrev superseva ***@***.***>:

**Comment by JohnBaystream** [comment]
Hi again

I forgot, i also saw that the different talent headlines in translation on the sheet got an extra s at the end. I don't think this can be solved with translation but has got to be how they are spelled the talents headlines on the original sheet?

For exampel: The mutants talents probably says "Mutanttalents" and the translation changes "Mutanttalent" to "Mutanttalang" but the s stays there so it says "Mutanttalangs".

Not sure how to change this.


All the +Add on the sheet doesnt change in translation, think "Add" should translate into "Lägg till". It doesn't matter so much since we have other similar swedish names like "Addera" wich means kinda the same.

24 augusti 2021 15:42:30 +02:00, skrev superseva ***@***.***>:

**Comment by JohnBaystream** [comment]
When i try to use the robot sheet it seems i can't use the Chassi part. So im not sure what each of these refers to? 
"MYZ.CHASSIS": "Chassidelar",
"ITEM.TypeChassis": "Chassidel",
Is the first the headline and the second when you choose chassi part? I think this is the right translation i hope. Since i cant use the Chassi part on the sheet i cant fully test what i change. 

Also i now see that another skillname for animals isn't correct translation since Know the Zone is the same for mutants/humans. Also the robots have three skillnames that wont translate correctly. All the programnames in swedish are unique. 

The word armor also gets a little tricky but think i solved it so it looks ok.

**Comment by JohnBaystream** [comment]
Think im done with the se.json file.

{
	"ACTOR.TypeAnimal": "Djurmutant",
	"ACTOR.TypeArk": "Ark",
	"ACTOR.TypeHuman": "Människa",
	"ACTOR.TypeMutant": "Mutant",
	"ACTOR.TypeNpc": "SLP",
	"ACTOR.TypeRobot": "Robot",
	"ITEM.TypeAbility": "Förmåga",
	"ITEM.TypeArmor": "Rustning",
	"ITEM.TypeArtifact": "Artefakt",
	"ITEM.TypeChassis": "Chassidel",
	"ITEM.TypeCritical": "Kritisk skada",
	"ITEM.TypeGear": "Utrustning",
	"ITEM.TypeProject": "Projekt",
	"ITEM.TypeSkill": "Färdighet",
	"ITEM.TypeTalent": "Talang",
	"ITEM.TypeWeapon": "Vapen",
	"MYZ.ABILITIES": "Förmågor",
	"MYZ.ABILITY_ANIMAL": "Djurförmåga",
	"MYZ.ABILITY_HUMAN": "Kontakt",
	"MYZ.ABILITY_MUTANT": "Mutation",
	"MYZ.ABILITY_ROBOT": "Modul",
	"MYZ.ABILITY_TYPE": "Förmåga",
	"MYZ.ACTOR_TYPE": "Arketyp",
	"MYZ.ADD": "Lägg till",
	"MYZ.AGE": "Ålder",
	"MYZ.ANIMAL": "Djur",
	"MYZ.ANIMAL_POWERS": "Djurförmågor",
	"MYZ.ARMOR": "Rustning",
	"MYZ.ARMOR_BODY": "Rustning",
	"MYZ.ARMOR_RATING": "Skyddsv.",
	"MYZ.ARMOR_SHIELD": "Sköld",
	"MYZ.ARMOR_TYPE": "Rustningstyp",
	"MYZ.ARTIFACT": "Artefakt",
	"MYZ.ARTIFACT_BONUS": "Artefaktbonus",
	"MYZ.ARTIFACTS": "Artefakter",
	"MYZ.ATTRIBUTE": "Grundegenskap",
	"MYZ.ATTRIBUTE_AGILITY_ANIMAL": "Kyla",
	"MYZ.ATTRIBUTE_AGILITY_HUMAN": "Kyla",
	"MYZ.ATTRIBUTE_AGILITY_MUTANT": "Kyla",
	"MYZ.ATTRIBUTE_AGILITY_ROBOT": "Stabilitet",
	"MYZ.ATTRIBUTE_EMPATHY_ANIMAL": "Instinkt",
	"MYZ.ATTRIBUTE_EMPATHY_HUMAN": "Känsla",
	"MYZ.ATTRIBUTE_EMPATHY_MUTANT": "Känsla",
	"MYZ.ATTRIBUTE_EMPATHY_ROBOT": "Nätverk",
	"MYZ.ATTRIBUTE_STRENGTH_ANIMAL": "Styrka",
	"MYZ.ATTRIBUTE_STRENGTH_HUMAN": "Styrka",
	"MYZ.ATTRIBUTE_STRENGTH_MUTANT": "Styrka",
	"MYZ.ATTRIBUTE_STRENGTH_ROBOT": "Servo",
	"MYZ.ATTRIBUTE_WITS_ANIMAL": "Skärpa",
	"MYZ.ATTRIBUTE_WITS_HUMAN": "Skärpa",
	"MYZ.ATTRIBUTE_WITS_MUTANT": "Skärpa",
	"MYZ.ATTRIBUTE_WITS_ROBOT": "Processor",
	"MYZ.ATTRIBUTES": "Grundegenskaper",
	"MYZ.BONUS": "Bonus",
	"MYZ.BOOZE": "Sprit",
	"MYZ.BOSS_NAME": "Bossnamn",
	"MYZ.BOSS_TYPE": "Bosstyp",
	"MYZ.BOSSES": "Bossar",
	"MYZ.BROKEN": "Bruten",
	"MYZ.BULLETS": "Patroner",
	"MYZ.CATEGORY": "Kategori",
	"MYZ.CHASSIS": "Chassidelar",
	"MYZ.COMMENT": "Kommentar",
	"MYZ.COMPLETED": "Slutfört",
	"MYZ.CONDITION_DEHYDRATED": "Uttorkad",
	"MYZ.CONDITION_HYPOTHERMIC": "Nedkyld",
	"MYZ.CONDITION_SLEEPLESS": "Sömnlös",
	"MYZ.CONDITION_STARVING": "Utsvulten",
	"MYZ.CONDITIONS": "Negativa tillstånd",
	"MYZ.CONSUMABLES": "Resurser",
	"MYZ.CONTACTS": "Kontakter",
	"MYZ.COORDINATES": "Koordinater",
	"MYZ.COST": "Kostnad",
	"MYZ.CRITICAL": "Kritisk skada",
	"MYZ.CRITICALS": "Kritiska skador",
	"MYZ.CULTURE": "Kultur",
	"MYZ.CUSTOM_ROLL": "Anpassat slag",
	"MYZ.DAMAGE": "Skada",
	"MYZ.DELETE": "Radera",
	"MYZ.DESCRIPTION": "Beskrivning",
	"MYZ.DEV_BONUS": "UN-bonus",
	"MYZ.DEV_LEVELS": "Utvecklingsnivåer",
	"MYZ.DEV_REQUIREMENT": "UN-krav",
	"MYZ.DICE_BASE": "Grundtärning",
	"MYZ.DICE_GEAR": "Pryltärning",
	"MYZ.DICE_SKILL": "Färdighetstärning",
	"MYZ.EDIT": "Editera",
	"MYZ.EFFECT": "Effekt",
	"MYZ.ENCUMBRANCE": "Belastning",
	"MYZ.EQUIPPED": "Buren",
	"MYZ.FOOD": "Krubb",
	"MYZ.GEAR": "Utrustning",
	"MYZ.GENERAL": "Allmän",
	"MYZ.GRUB": "Krubb",
	"MYZ.HEAD": "Huvud",
	"MYZ.HEALINGTIME": "Läkningstid",
	"MYZ.HUMAN": "Människa",
	"MYZ.INFO": "Info",
	"MYZ.LETHAL": "Dödlig",
	"MYZ.LOCATION": "Plats",
	"MYZ.MODIFIER": "Modifikation",
	"MYZ.MODULES": "Moduler",
	"MYZ.MUTANT": "Mutant",
	"MYZ.MUTANT_YEAR_ZERO": "Mutant År Noll",
	"MYZ.MUTATIONS": "Mutationer",
	"MYZ.NAME": "Namn",
	"MYZ.NO_COMBAT_SKILL": "Ingen Stridsfärdighet vald [Slåss eller Skjuta]",
	"MYZ.NUMBER_OF_MODULES": "Antal moduler",
	"MYZ.OTHER_REQUIREMENTS": "Övriga krav",
	"MYZ.PERMA_ROT": "Permanent röta",
	"MYZ.PICK_NPC_TYPE": "VÄLJ SLP-TYP",
	"MYZ.POPULATION": "Invånarantal",
	"MYZ.PROJECTS": "Projekt",
	"MYZ.PUSH": "Pressa",
	"MYZ.PUSHED": "Pressad",
	"MYZ.QUANTITY": "Antal",
	"MYZ.RANGE": "Avstånd",
	"MYZ.RANGE_ARM": "Armslängd",
	"MYZ.RANGE_DISTANT": "Distans",
	"MYZ.RANGE_LONG": "Långt",
	"MYZ.RANGE_NEAR": "Nära",
	"MYZ.RANGE_SHORT": "Kort",
	"MYZ.RANK_FOR_ANIMAL": "Rang",
	"MYZ.RANK_FOR_HUMAN": "Rykte",
	"MYZ.RANK_FOR_MUTANT": "Rang",
	"MYZ.RANK_FOR_ROBOT": "Hierarki",
	"MYZ.REQUIREMENT": "Krav",
	"MYZ.RESOURCE_POINTS_ANIMAL": "Vildsinnespoäng",
	"MYZ.RESOURCE_POINTS_HUMAN": "Inflytandepoäng",
	"MYZ.RESOURCE_POINTS_MUTANT": "Mutationspoäng",
	"MYZ.RESOURCE_POINTS_ROBOT": "Energipoäng",
	"MYZ.ROBOT": "Robot",
	"MYZ.ROLE": "Roll",
	"MYZ.ROLE_FOR_ANIMAL": "Syssla",
	"MYZ.ROLE_FOR_HUMAN": "Yrke",
	"MYZ.ROLE_FOR_MUTANT": "Syssla",
	"MYZ.ROLE_FOR_ROBOT": "Modell",
	"MYZ.ROLL": "Slå",
	"MYZ.ROT": "Zonröta",
	"MYZ.SEASON": "Årstid",
	"MYZ.SECONDARY_FUNCTION": "Sekundärfunktion",
	"MYZ.SECONDARY_FUNCTIONS": "Sekundärfunktioner",
	"MYZ.SHIELD": "Sköld",
	"MYZ.SKILL_ANALYZE": "Analysera",
	"MYZ.SKILL_ASSAULT": "Bekämpa",
	"MYZ.SKILL_BREWPOTION": "Brygga dekokt",
	"MYZ.SKILL_BONUS": "Färdighetsbonus",
	"MYZ.SKILL_CALCULATE": "Kalkylera",
	"MYZ.SKILL_CLEAN": "Rengöra",
	"MYZ.SKILL_COMMAND": "Kommendera",
	"MYZ.SKILL_COMMANDOFFICER": "Beordra",
	"MYZ.SKILL_COMPREHEND": "Förstå sig på",
	"MYZ.SKILL_COORDINATE": "Koordinera",
	"MYZ.SKILL_DATAMINE": "Datasöka",
	"MYZ.SKILL_DOMINATE": "Dominera",
	"MYZ.SKILL_ENDURE": "Kämpa på",
	"MYZ.SKILL_ENLIGHTEN": "Upplysa",
	"MYZ.SKILL_FIGHT": "Slåss",
	"MYZ.SKILL_FINDTHEPATH": "Leda vägen",
	"MYZ.SKILL_FORCE": "Ta krafttag",
	"MYZ.SKILL_HEAL": "Vårda",
	"MYZ.SKILL_HUNT": "Jaga",
	"MYZ.SKILL_INFILTRATE": "Infiltrera",
	"MYZ.SKILL_INSPIRE": "Inspirera",
	"MYZ.SKILL_INTERACT": "Interagera",
	"MYZ.SKILL_INTIMIDATE": "Mucka",
	"MYZ.SKILL_INVESTIGATE": "Undersöka",
	"MYZ.SKILL_JURYRIG": "Mecka",
	"MYZ.SKILL_KNOWTHEZONE": "Känna Zonen",
	"MYZ.SKILL_MAKEADEAL": "Schackra",
	"MYZ.SKILL_MANIPULATE": "Manipulera",
	"MYZ.SKILL_MANIPULATEPROGRAM": "Manipulera",
	"MYZ.SKILL_MANUFACTURE": "Tillverka",
	"MYZ.SKILL_MEASUREENEMY": "Skärskåda",
	"MYZ.SKILL_MOVE": "Fly",
	"MYZ.SKILL_OVERLOAD": "Överbelasta",
	"MYZ.SKILL_PRESSON": "Bita ihop",
	"MYZ.SKILL_PROSECUTE": "Lagföra",
	"MYZ.SKILL_PROTECT": "Skydda",
	"MYZ.SKILL_QUESTION": "Ifrågasätta",
	"MYZ.SKILL_RECYCLE": "Återvinna",
	"MYZ.SKILL_REPAIR": "Reparera",
	"MYZ.SKILL_SCAN": "Sondera",
	"MYZ.SKILL_SCAVENGE": "Samla",
	"MYZ.SKILL_SCOUT": "Speja",
	"MYZ.SKILL_SCRY": "Sia",
	"MYZ.SKILL_SENSEEMOTION": "Genomskåda",
	"MYZ.SKILL_SHAKEITOFF": "Uthärda",
	"MYZ.SKILL_SHOOT": "Skjuta",
	"MYZ.SKILL_SICADOG": "Bussa på",
	"MYZ.SKILL_SNEAK": "Smyga",
	"MYZ.SKILL_TARGET": "Målsöka",
	"MYZ.SKILL_TINKER": "Mixtra",
	"MYZ.SKILLS": "Färdigheter",
	"MYZ.SKILLS_LABEL_ANIMAL": "Färdigheter",
	"MYZ.SKILLS_LABEL_HUMAN": "Färdigheter",
	"MYZ.SKILLS_LABEL_MUTANT": "Färdigheter",
	"MYZ.SKILLS_LABEL_ROBOT": "Program",
	"MYZ.SPECIAL": "Special",
	"MYZ.SPECIFIC_TYPE_FOR_ANIMAL": "Djurart",
	"MYZ.SPECIFIC_TYPE_FOR_HUMAN": "Ätt",
	"MYZ.SPECIFIC_TYPE_FOR_MUTANT": "Mutant",
	"MYZ.SPECIFIC_TYPE_FOR_ROBOT": "Personlighet",
	"MYZ.STATS": "Värde",
	"MYZ.STUNTS": "Bonuseffekter",
	"MYZ.TALENT": "Talang",
	"MYZ.TALENT_ANIMAL": "Djurtalang",
	"MYZ.TALENT_HUMAN": "Människotalang",
	"MYZ.TALENT_MUTANT": "Mutanttalang",
	"MYZ.TALENT_ROBOT": "Sekundärfunktion",
	"MYZ.TALENT_SOURCE": "Talangkälla",
	"MYZ.TALENT_TYPE": "Talangtyp",
	"MYZ.TALENTS": "Talanger",
	"MYZ.TECHNOLOGY": "Teknologi",
	"MYZ.TIMELIMIT": "Tidsgräns",
	"MYZ.TORSO": "Bål",
	"MYZ.TYPE": "Typ",
	"MYZ.UNDERCARRIAGE": "Underrede",
	"MYZ.VALUE": "Värde",
	"MYZ.WARFARE": "Försvar",
	"MYZ.WATER": "Vatten",
	"MYZ.WATER_SOURCE": "Vattenkälla",
	"MYZ.WEAPON": "Vapen",
	"MYZ.WEAPON_MELEE": "Närstrid",
	"MYZ.WEAPON_RANGED": "Avstånd",
	"MYZ.WEAPONS": "Vapen",
	"MYZ.WEIGHT": "Vikt",
	"MYZ.WEIGHT_HEAVY": "Tung",
	"MYZ.WEIGHT_LIGHT": "Lätt",
	"MYZ.WEIGHT_REGULAR": "Vanlig",
	"MYZ.WEIGHT_TINY": "Småpryl",
	"MYZ.WEIGHTLESS": "Viktlös",
	"MYZ.WORK_POINTS": "Arbetspoäng",
	"MYZ.XP": "ERF"
}

**Comment by JohnBaystream** [comment]
These are tricker but think something like this works.

"SETTINGS.ApplyPushTraumaN": "Ta pressad trauma",
"SETTINGS.ApplyPushTraumaH": "Ta trauma från "ETTOR" på pressade slag.",
"SETTINGS.ApplyPushGearDamageN": "Ta pressad prylskada",
"SETTINGS.ApplyPushGearDamageH": "Ta prylskada från "ETTOR" på pressade slag."

Like i said before the word bane doesn´t exist in the swedish version they only show the symbol. Never give it a name. Think it might be called TOXIC for basedice and EXPLO for geardice but thats not real words in swedish. "ETTOR" just means "ONES". Can i use quotation marks around the word ETTOR inside the other quotation marks?

**Comment by JohnBaystream** [comment]
Just realized that i didn´t understand your initial part regarding push release. I'm new to GIThub so havent learned all the ropes yet.
