### ISSUE TITLE
Problem in encumbrance calculus

### ISSUE THREAD

**Issue by Gyaile** [superseva/mutant-year-zero#42]
In the actor.js file line 65, the encumbrance calculus of the bullets is : 
_totalWeight += parseInt(data.resources.bullets.value) / 10;
It should be :
_totalWeight += parseInt(data.resources.bullets.value) / 20; according to the rules. 10 bullets count as a tiny item and 20 bullets as a regular item.

**Comment by superseva** [comment]
oh. I'll fix it in the next update.
Thanks for noticing it

**Comment by superseva** [comment]
fixed
