### ISSUE TITLE
Question about packs translation

### ISSUE THREAD

**Issue by Petwag** [superseva/mutant-year-zero#47]
Good morning, I was thinking about translating the packs with the help of babel to apply the translation. 
Do you think the translation could be a part of that repo? something like a folder /fr-FR inside /packs for example?

Then the user can just use babel and give the path for the translation to apply?

**Comment by superseva** [comment]
Hi, I would need to check what is babel and how it works. The skill pack is used on character creation and each skill has a hidden filed that contains the ID of a skill. I need to see how that would work when creating a new character

**Comment by superseva** [comment]
This thing is also checking if there is an official content present so it pick the package from the official book if found... So it might require some taping in to that too

**Comment by Petwag** [comment]
I did some translation for another game and the way babel was working was that it was using the name of the original record as a key and then override dynamiccaly with the french translation. So it is not affecting the record itself and it is keeping the uniques ids.

**Comment by superseva** [comment]
So the skill-pack only contains the names of the skills and that should be already translatable through the fr.json translation json.
all the entries starting with SKILL_*** should translate the skill names on the sheet.
We can't translate the official content. That is something Free League must do

**Comment by Petwag** [comment]
Yes for the official content I understand, I didn't plan on putting my translation here

**Comment by superseva** [comment]
I took a look at babel, I am just curios what would you get with it since the only things in pack are the skill names, and those are already translatable ?

**Comment by Petwag** [comment]
I didn't know they were translatable like this, then we indeed don't need babel

**Comment by superseva** [comment]
I am not sure if the fr translation is all up to date. The best way is to download en.json and compare if all the enetries are present in fr version
If you find any discrepancies just put it here and I can update

**Comment by superseva** [comment]
I get something like this if I change the system language to Fr
![Foundry_Virtual_Tabletop_5riN4mBjg6](https://user-images.githubusercontent.com/4093045/150396531-e8bc080c-faf5-4c71-8c3f-6981d23eb9c9.png)

**Comment by Petwag** [comment]
Yes you are right, I think I messed something on my side. My bad

**Comment by Petwag** [comment]
Not a big deal but it's in fact when we open the skill that the translation does not appear
![image](https://user-images.githubusercontent.com/9394037/150400151-bd6a7dde-1f75-47c2-a8ff-9c0edf98c10e.png)

That is what babel is used for.
But anyway we don't need that I think

**Comment by superseva** [comment]
You can still use Babel if you need it but I would like to avoid putting any Module related files in to the system and make system dependent of the module existence.
