### ISSUE TITLE
initiative roll

### ISSUE THREAD

**Issue by NendoSan** [superseva/mutant-year-zero#5]
Initiative roll should be 1d6 + agility score and not 1d6 + agility/10 (accordind to the rules from 2014, p79).
However in the v2 of the rules it is 1d6 cf [https://forum.frialigan.se/viewtopic.php?f=111&t=2556](url)

**Comment by superseva** [comment]
i've setup initiative to be 1d6 according to updated V2 rules.
Agility/10 is there just as a convenient way to separate the same roll results if needed be but you can ignore that decimal space.

**Comment by NendoSan** [comment]
Ok, no problem here, I just found weird to see decimal in the result.
Btw, I like what you have done so far, thank you !
