### ISSUE TITLE
System duplicates actor items if there is 2 or more GMs/Assistant GMs

### ISSUE THREAD

**Issue by bithir** [superseva/mutant-year-zero#52]
If you have a system with one GM and an assistant GM and creates a character, it duplicates the skills.
![image](https://user-images.githubusercontent.com/19734037/178159209-6d71c44b-9b5b-4112-b2bf-3eb1eac4fa86.png)

**Comment by superseva** [comment]
Finally Fixed.
Sorry for the long wait
v10.0.7
