### ISSUE TITLE
Added "s" to the end of Talents in the Swedish sheet

### ISSUE THREAD

**Issue by Martin-Joensson** [superseva/mutant-year-zero#53]
Should be just, "Mutanttalang"

![Screenshot 2022-09-03 at 20 12 01](https://user-images.githubusercontent.com/110732661/188283204-4fc54c5d-89b2-42e0-a89f-5d6dc13b015e.png)

**Comment by superseva** [comment]
I’ll fix the translation. Thanks for reporting it.

**Comment by saeldion** [comment]
Even though removing the "s" would make it better on the swedish character sheets they are just called "Talanger" excluding Mechatron where it's "Sekundärfunktioner". Don't know if the goal is to reflect the character sheet?

**Comment by superseva** [comment]
I've added more translation keys for the plurals version of talents. I am not speaking Swedish  so I recommend to go through the se.json and check things out. The best way is to make changes and then create a Pull Request
