### ISSUE TITLE
Booze - 10 doses, weight

### ISSUE THREAD

**Issue by Kariaudhanaur** [superseva/mutant-year-zero#65]
Hello ! :)
For the booze, if we put 1 on the character sheet, we can see the weight of 1... But as it's for 10 doses, would it be possible to handle decimals please ? 
For example, 0.8 in booze could mean "8 doses on 1 bottle of 10", and a weight of 0.8 ... ?
Thanks !

**Comment by superseva** [comment]
sorry for the late reply.
I have added this in the version 10.0.6. I am testing the rest of the updates and pushing it soon
