### ISSUE TITLE
Some wrong translations into German

### ISSUE THREAD

**Issue by KaiderWeise** [superseva/mutant-year-zero#68]
Wrong: "MYZ.SKILL_ASSAULT": "**Angreifen**"    -> Correct: "MYZ.SKILL_ASSAULT": "**Angriff**"
Wrong: "MYZ.ATTRIBUTE_WITS_ROBOT": "**Processor**"    -> Correct: "MYZ.ATTRIBUTE_WITS_ROBOT": "**Prozessor**"
Wrong: "MYZ.TALENTS_ROBOT": "**Secondary Functions**"    -> Correct: "MYZ.TALENTS_ROBOT": "**Sekundäre Funktionen**"
W: "ITEM.TypeArmor": "**Rüstung**" -> C: "ITEM.TypeArmor": "**Panzerung**"
W: "MYZ.ARMOR": "**Rüstung**"  -> C: "MYZ.ARMOR": "**Panzerung**"
W: "MYZ.ARMOR_BODY": "**Rüstung**"  -> C: "MYZ.ARMOR_BODY": "**Panzerung**"

**Comment by KaiderWeise** [comment]
Wrong: "MYZ.SKILL_INFILTRATE": "**Infiltrieren**" -> Correct: "MYZ.SKILL_INFILTRATE": "**Infiltration**"

**Comment by KaiderWeise** [comment]
Wrong: "MYZ.TORSO": "**Körper**" -> Correct: "MYZ.TORSO": "**Torso**"
Wrong: "MYZ.UNDERCARRIAGE": "**Innenleben**" -> Correct: "MYZ.UNDERCARRIAGE": "**Fahrgestell**"

**Comment by KaiderWeise** [comment]
Wrong: "MYZ.XP": "**XP**" -> Correct: "MYZ.XP": "**EP**"

**Comment by superseva** [comment]
Could you please open a pull request or just send me the complete json for the updated german translation.

**Comment by KaiderWeise** [comment]
I can send you the de.json, but how?

**Comment by superseva** [comment]
send it to superseva@gmail.com
thanks!
