### ISSUE TITLE
Find the Path skill modifications not passed from talents, mutations or gear.

### ISSUE THREAD

**Issue by fugmulch** [superseva/mutant-year-zero#71]
I am having an issue with MYZ (core rules) and the Find the Path skill.

Modifications for gear, talents or abilities are not added to the skill roll when they are given a non-zero value in the modifications tab.  Does not function for either a skill or gear modification, either positive or negative.

![image](https://user-images.githubusercontent.com/7998395/224402578-fe2467a2-e4f8-474d-b591-5a48396ad5df.png)

**Comment by superseva** [comment]
probably a manually created skill. Use the imported skills or the one from the system/core-book compendium
