### ISSUE TITLE
Some words on the character sheet are impossible to translate

### ISSUE THREAD

**Issue by Kariaudhanaur** [superseva/mutant-year-zero#76]
As displayed in the picture, you can see that 
![image](https://user-images.githubusercontent.com/92259502/234971712-5ddf5659-7ea6-45f5-9076-867cf52d7a7d.png)
Tooltips : "to chat" "edit" "stash" "delete" => impossible to translate
On the sheet : "+Add" => impossible to translate

If it's possible to make this happen...

Thanks :)

**Comment by superseva** [comment]
Fixed
