### ISSUE TITLE
Created ability rolls

### ISSUE THREAD

**Issue by pplurueda** [superseva/mutant-year-zero#77]
When you try to make a roll with a created ability (e.g. special role abilities) at hand, you get an error.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/82481289/235315231-fca96e2f-3fc1-44d8-96e1-82d54072fbd3.png">

**Comment by superseva** [comment]
Hi, I am not sure what you mean by "special role abilities" ?

**Comment by superseva** [comment]
You mean skill ?
I see the error if you create the skill manually.

You should not create those manually but always drag them from the skill compendium.
You would only want to crate custom one if your setting have some skill that is not in the books.
 I'll fix it but you should not create skills from the books manually but drag and drop ones from the compendium skills.
Each skill in the compendium has a skill-key property and that is used by the system. If you create one by hand you can't assign modifiers to it nor you can have stunts.

**Comment by superseva** [comment]
Fixed.
But a reminder, if the skill is from the book drag it from the skill compendium. Don't create it manually.
