### ISSUE TITLE
Duplicated skills

### ISSUE THREAD

**Issue by pplurueda** [superseva/mutant-year-zero#83]
When duplicating an actor, other than an NPC, with the context menu option, the actor being created has all skills duplicated.
Thank you very much for the work done.

**Comment by superseva** [comment]
Should be fixed now. V 10.0.11
A remnant from the update to Foundry v10 that I missed.
Thanks for reporting

**Comment by pplurueda** [comment]
The same thing keeps happening to me with version 10.0.11.

<img width="725" alt="image" src="https://github.com/superseva/mutant-year-zero/assets/82481289/833a9203-0cb8-4538-b31f-1ddbfb329343">

**Comment by superseva** [comment]
Sorry my mistake. I fixed it and uploaded old version yesterday.
New version is up v10.0.12
