### ISSUE TITLE
Descomposition rolls

### ISSUE THREAD

**Issue by pplurueda** [superseva/mutant-year-zero#86]
The decomposition section (I don't know the exact term) has some strange behaviour:

1. Modifying the permanent decomposition automatically updates the temporary decomposition to the same value.
2. When making a decomposition roll, a base die is not added for each decomposition point, whether temporary or permanent.

<img width="203" alt="image" src="https://github.com/superseva/mutant-year-zero/assets/82481289/e640ccc7-74dd-4b7f-89b7-1334142a3d67">
<img width="205" alt="image" src="https://github.com/superseva/mutant-year-zero/assets/82481289/f7bfd0f2-fbdc-4fdd-afc4-defcaef966d0">

**Comment by superseva** [comment]
I’ll check it after weekend. Thanks for notifying me. Temp rot should never be lower that Permanent I believe is what automation doing but I will check.

**Comment by superseva** [comment]
I have decoupled the Rot and Permanent Rot. I see how it might be confusing before.
Now they are not connected. When rolling total rot  is now  current + permanent.
Look for the updated MYZ v10.0.13
