### ISSUE TITLE
Swedish character sheet

### ISSUE THREAD

**Issue by faust74swe** [superseva/mutant-year-zero#89]
On the Swedish Mutant and Human sheets the attribute Empati is ment to be called Känsla and the Swedish name for the skill Sense Emotion is names Sniffa but is ment to be names Genomskåda.

**Comment by superseva** [comment]
Hey Faust, thanks for pointing that out. I am not a Swedish speaker so the translation is done one or two times already by people submitting the translated file to the system. I guess it should be done as it is on the paper version of the Swedish sheet. Although I don't have one
