### ISSUE TITLE
ER - Encumbrance - Deal with talent like "Pack mule"

### ISSUE THREAD

**Issue by Kariaudhanaur** [superseva/mutant-year-zero#95]
Is it possible to have some parameters to modify / update / multiply values of the character sheet ? 

The first idea is with Pack mule : You can carry twice as many objects as normal without being encumbered (page 23).

It seems impossible for the moment to have the double of the encumbrance limit (to avoid "red cell" when there is no overweight)

Thanks ! :)

**Comment by superseva** [comment]
Shouldn't just dragging talent with the name "Pack Mule" just do it automatically ?

**Comment by Kariaudhanaur** [comment]
Didn't work last time...
I'll try again today and let you know

**Comment by Kariaudhanaur** [comment]
You're right... it's working... But only in english ^^
In french, "Mule", doesn't work.
Is there a way to translate this sort of automation you hard coded somewhere ?
Thank you

**Comment by superseva** [comment]
Oh, yeah. Talents are not translated, but if you want you can create Active Effect on the actor

Modify `system.encumbranceMax` on Active Effect Tab. You can Add/Override the value there

**Comment by Kariaudhanaur** [comment]
Indeed, it works perfectly ! Thank you, I'll use it that way ^^

**Comment by Kariaudhanaur** [comment]
Perfect workaround :)
